logsBucket: gs://gcsterraform-bucket

steps:
  # Step 1: Terraform Init
  - name: 'hashicorp/terraform:light'
    id: terraform-init
    dir: 'compute'
    args: ['init']

  # Step 2: Terraform Plan
  - name: 'hashicorp/terraform:light'
    id: terraform-plan
    dir: 'compute'
    args: ['plan', '-out=tfplan']

  # Step 3: Terraform Apply
#  - name: 'hashicorp/terraform:light'
#    id: terraform-apply
#    dir: 'compute'
 #   args: ['apply', '-auto-approve', 'tfplan']
  - name: 'hashicorp/terraform:light' 
    id: terraform-destroy 
    dir: 'compute' 
    args: ['destroy', '-auto-approve']

serviceAccount:  projects/my-main-host-project-480709/serviceAccounts/terraform@my-main-host-project-480709.iam.gserviceaccount.com


# Cloud Build substitutions (optional)
substitutions:
  _TF_DIR: "."

# Timeout for the build
timeout: "1200s"


