logsBucket: gs://gcsterraform-bucket

steps:
  # Step 1: Terraform Init
  - name: 'hashicorp/terraform:light'
    id: terraform-init
    dir: 'compute'   # adjust to the folder where your main.tf lives
    args: ['init']

  # Step 2: Terraform Destroy
  - name: 'hashicorp/terraform:light'
    id: terraform-destroy
    dir: 'compute'
    args: ['destroy', '-auto-approve']



serviceAccount:  projects/my-main-host-project-480709/serviceAccounts/terraform@my-main-host-project-480709.iam.gserviceaccount.com


# Cloud Build substitutions (optional)
substitutions:
  _TF_DIR: "."


# Timeout for the build
timeout: "1200s"
