logsBucket: gs://gcsterraform-bucket

steps:
  # Step 1: Terraform Init
  - name: 'hashicorp/terraform:light'
    id: terraform-init
    dir: '*'
    args: ['init']

  # Step 2: Terraform Plan
  - name: 'hashicorp/terraform:light'
    id: terraform-plan
    dir: '*'
    args: ['plan', '-out=tfplan']

  # Step 3: Terraform Apply
  - name: 'hashicorp/terraform:light'
    id: terraform-apply
    dir: '*'
    args: ['apply', '-auto-approve', 'tfplan']

serviceAccount:  projects/my-main-host-project-480709/serviceAccounts/terraform@my-main-host-project-480709.iam.gserviceaccount.com


# Cloud Build substitutions (optional)
substitutions:
  _TF_DIR: "."

# Timeout for the build
timeout: "1200s"


