logsBucket: gs://gcsterraform-bucket

  # Step 2: Terraform Destroy
  - name: 'hashicorp/terraform:light'
    id: terraform-destroy
    dir: 'compute'
    args: ['destroy', '-auto-approve']

# Service account to run the build (replace with your SA email)


serviceAccount:  projects/my-main-host-project-480709/serviceAccounts/terraform@my-main-host-project-480709.iam.gserviceaccount.com


# Cloud Build substitutions (optional)
substitutions:
  _TF_DIR: "."


# Timeout for the build
timeout: "1200s"
